services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./volumes/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always

